import math

# Game Settings
RES = WIDTH, HEIGHT = 1600, 800
RES_SCALE = SCALE_WIDTH, SCALE_HEIGHT = 320*1.5, 160*1.5   #Proper scale res
#RES_SCALE = SCALE_WIDTH, SCALE_HEIGHT = WIDTH, HEIGHT   #zoomed out
FPS = 60

TILE_SIZE = 32

MAGIC_NUM = 3

VISABLE_TRIGGER = True

SHADOW = False
